import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { HeroUIProvider } from '@heroui/system';
import { GoogleAnalytics } from '@next/third-parties/google';

const inter = Inter({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<HeroUIProvider>
			<html lang='en'>
				<body className={`${inter.variable} antialiased`}>
					{children}
					<GoogleAnalytics gaId={process.env.GID!} />
				</body>
			</html>
		</HeroUIProvider>
	);
}
